name: Set Global Variables

outputs:
  EmailRecipient: 
    value: ${{ steps.globals.outputs.EmailRecipient }}
  CICDKey: 
    value: ${{ steps.globals.outputs.CICDKey }}
    
runs:
  using: composite

  steps:
   - name: Set GLobal Variables
     shell: bash
     id: globals
     working-directory: ${{ github.action_path }}
     run: |
       chmod +x globals.sh
       ./globals.sh
