name: Build Angular App
  
on:     
  push:
    branches: [ main ]
  workflow_dispatch:
     
jobs:
  build-deploy:
    uses: ./.github/workflows/reusable-build-deploy-angular.yml
    with:
      pythonVersion: 3.10
      nodejsVersion: 18.20.4
