name: Build Angular App
  
on:     
  push:
    branches: [ main ]
  workflow_dispatch:
     
jobs:
  build-deploy:
    uses: InterviewProOrg/BuildDeployAngular/.github/workflows/reusable-build-deploy-angular.yml@main 
    secrets:
      PASSWORD: ${{ secrets.PASSWORD }}
    with:
      pythonVersion: 3.10
      nodejsVersion: 18.20.4
