name: Deploy Angular App

on:
  workflow_dispatch:

jobs:
  deploy-angular:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: artifact
          run-id: 9627516506

      - name: Display structure of downloaded files
        run: ls -R artifact
