name: Deploy Angular App

on:
  workflow_dispatch:

jobs:
  deploy-angular:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          name: build-artifact
          path: artifact
          workflow: build-angular.yml
          github_token: ${{ github.token }}
          repo: ${{ github.repository }}
          run_number: 27

      - name: Display structure of downloaded files
        run: ls -R artifact
