name: Environments2

on:
  workflow_dispatch:

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Deploy
        run: |
          echo "Deployed to DEV"
          echo "Environment Variable - ${{vars.TEST_VAR}}"

  STAGE:
    runs-on: ubuntu-latest
    environment: Stage
  
    steps:
      - name: Deploy
        run: |
          echo "Deployed to Stage"      
          echo "Environment Variable - ${{vars.TEST_VAR}}"

  PROD:
    runs-on: ubuntu-latest
    environment: Prod

    steps:
      - name: Deploy
        run: |
          echo "Deployed to Prod"    
          echo "Environment Variable - ${{vars.TEST_VAR}}"
          
