name: Environments

on:
  workflow_dispatch:

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Deploy
        run: echo "Deployed to DEV"

  STAGE:
    runs-on: ubuntu-latest
    environment: Stage
    needs: DEV
    steps:
      - name: Deploy
        run: echo "Deployed to Stage"      

  PROD:
    runs-on: ubuntu-latest
    environment: Prod
    needs: STAGE
    steps:
      - name: Deploy
        run: echo "Deployed to Prod"    
