name: Environments

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Test deployment"
          echo "USERNAME = ${{vars.USERNAME}}"
          echo "PASSWORD = ${{secrets.PASSWORD}}"
          
  DEV:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Deploy
        run: |
          echo "Deployed to DEV"
          echo "USERNAME = ${{vars.USERNAME}}"
          echo "PASSWORD = ${{secrets.PASSWORD}}"

  STAGE:
    runs-on: ubuntu-latest
    needs: DEV
    environment: Stage
  
    steps:
      - name: Deploy
        run: |
          echo "Deployed to Stage"      
          echo "USERNAME = ${{vars.USERNAME}}"
          echo "PASSWORD = ${{secrets.PASSWORD}}"
          
  PROD:
    runs-on: ubuntu-latest
    needs: STAGE
    environment: Prod

    steps:
      - name: Deploy
        run: |
            echo "Deployed to Prod"    
            echo "USERNAME = ${{vars.USERNAME}}"
            echo "PASSWORD = ${{secrets.PASSWORD}}"
