name: Global Variables

on:
   workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set Global Variables
        id: globals
        uses: ./.github/actions/SetGlobalVariables

      - name: Log Global Variables
        run: |
          echo "Email Recipient = ${{ steps.globals.outputs.EmailRecipient }}"
        
