name: Set Global Variables

on:
   workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set Global Variables
        uses: ./.github/actions/SetGlobalVariables
        
