name: Init

on: 
 workflow_call:
   inputs:
     packages:
       required: true
       type: string

   outputs:
     DEPLOY_PKG1:
        description: "Deploy package 1"
        value: ${{ jobs.get-packages.outputs.deploy_pkg1 }}
     DEPLOY_PKG2:
        description: "Deploy pkg2"
        value: ${{ jobs.get-packages.outputs.deploy_pkg2 }}
     DEPLOY_PKG3:
        description: "Deploy pkg3"
        value: ${{ jobs.get-packages.outputs.deploy_pkg3 }}
     DEPLOY_PKG4:
        description: "Deploy pkg4"
        value: ${{ jobs.get-packages.outputs.deploy_pkg4 }}
     DEPLOY_PKG5:
        description: "Deploy pkg5"
        value: ${{ jobs.get-packages.outputs.deploy_pkg5 }}        
     PKG1_VERSION:
        value: ${{ jobs.get-packages.outputs.deploy_pkg1 }} 
     PKG2_VERSION:
        value: ${{ jobs.get-packages.outputs.deploy_pkg2 }} 
     PKG3_VERSION:
        value: ${{ jobs.get-packages.outputs.deploy_pkg3 }} 
     PKG4_VERSION:
        value: ${{ jobs.get-packages.outputs.deploy_pkg4 }} 
     PKG5_VERSION:
        value: ${{ jobs.get-packages.outputs.deploy_pkg5 }} 
        
jobs:
  Init:
    runs-on: windows-latest

    outputs:
      deploy_pkg1: ${{ steps.set.outputs.deploy_pkg1 }}
      deploy_pkg2: ${{ steps.set.outputs.deploy_pkg2 }}
      deploy_pkg3: ${{ steps.set.outputs.deploy_pkg3 }}
      deploy_pkg4: ${{ steps.set.outputs.deploy_pkg4 }}
      deploy_pkg5: ${{ steps.set.outputs.deploy_pkg5 }}
      version_pkg1: ${{ steps.set.outputs.version_pkg1 }}
      version_pkg2: ${{ steps.set.outputs.version_pkg2 }}
      version_pkg3: ${{ steps.set.outputs.version_pkg3 }}
      version_pkg4: ${{ steps.set.outputs.version_pkg4 }}
      version_pkg5: ${{ steps.set.outputs.version_pkg5 }}
      
    steps:
      - name: Get config file
        shell: pwsh
        run: |
          Write-Host "Retrieving config file ..."

      - name: Get pacakges to deploy
        id: get-packages
        shell: pwsh
        run: |
          $inputString = '${{ inputs.packages }}'
          $packageMap = @{}

          foreach ($pair in $inputString -split ',') {
            $trimmed = $pair.Trim()
            if ($trimmed -match '=') {
              $name, $version = $trimmed -split '=', 2
              $packageMap[$name] = $version
            }
          }

          $deploy_pkg1 = $packageMap.ContainsKey('pkg1')
          $deploy_pkg2 = $packageMap.ContainsKey('pkg2')
          $deploy_pkg3 = $packageMap.ContainsKey('pkg3')
          $deploy_pkg4 = $packageMap.ContainsKey('pkg4')
          $deploy_pkg5 = $packageMap.ContainsKey('pkg5')

          $pkg1_version = $packageMap['pkg1']
          $pkg2_version = $packageMap['pkg2']
          $pkg3_version = $packageMap['pkg3']
          $pkg4_version = $packageMap['pkg4']
          $pkg5_version = $packageMap['pkg5']

          Write-Output "deploy_pkg1=$deploy_pkg1" >> $GITHUB_OUTPUT
          Write-Output "deploy_pkg2=$deploy_pkg2" >> $GITHUB_OUTPUT
          Write-Output "deploy_pkg3=$deploy_pkg3" >> $GITHUB_OUTPUT
          Write-Output "deploy_pkg4=$deploy_pkg4" >> $GITHUB_OUTPUT
          Write-Output "deploy_pkg5=$deploy_pkg5" >> $GITHUB_OUTPUT

          Write-Output "pkg1_version=$pkg1_version" >> $GITHUB_OUTPUT
          Write-Output "pkg2_version=$pkg2_version" >> $GITHUB_OUTPUT
          Write-Output "pkg3_version=$pkg3_version" >> $GITHUB_OUTPUT
          Write-Output "pkg4_version=$pkg4_version" >> $GITHUB_OUTPUT
          Write-Output "pkg5_version=$pkg5_version" >> $GITHUB_OUTPUT

      
        
