name: Job output

on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
       job1_name: ${{steps.set-output.outputs.name}}
       
    steps:
      - name: set output
        id: set-output
        run: |
          echo "name=InterviewPro" >> $GITHUB_OUTPUT
          echo "age=12" >> $GITHUB_ENV

      - name: access output
        run: |
          echo "value of name is ${{steps.set-output.outputs.name}}"
          echo "age is $env:age "

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
     - name: access output
       run: echo "value of output name from job1 is ${{needs.job1.outputs.job1_name }}"
