name: Build and Deploy Angular App

on:
  workflow_call:
    inputs:
      pythonVersion:
        required: true
        type: string
      nodejsVersion:
        required: true
        type: string

jobs:
  build-angular:
    runs-on: ubuntu-latest
    concurrency:
     group: ci-${{ github.workflow }}
     cancel-in-progress: true
     
    steps: 
      - uses: actions/checkout@v4
      
      - name: Setup Build Environemnt
        id: setup-build-env
        uses: ./.github/actions/SetupBuildEnvironment
        with:
          pythonVersion: ${{ inputs.pythonVersion }}
          nodejsVersion: ${{ inputs.nodejsVersion }}

      - name: Outputs from action
        run: |
          echo "Repository owner = ${{steps.setup-build-env.outputs.repoOwner }}"
          echo "Default Branch = ${{steps.setup-build-env.outputs.defaultBranch }}"
          echo "CI CD Key = ${{steps.setup-build-env.outputs.cicdKey }}"
          
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Sleep
        run: sleep 10

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist   
          
  deploy-angular:
    runs-on: ubuntu-latest
    needs: build-angular

    concurrency:
     group: cd-${{ github.workflow }}
     cancel-in-progress: true
     
    steps: 
      - name: Sleep
        run: sleep 60        
