name: Scheduled workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * 6'

jobs:
  demo:
    runs-on: ubuntu-latest

    steps: 
      - name: Greetings
        run: echo "Hello, world!"
