name: Step output

on:
 push: 
  branches: [main]

jobs:
  job1:
    runs-on: windows-latest

    steps:
      - name: Set output
        id: set-output
        run: echo "age=23" >> $GITHUB_OUTPUT

      - name: Use output
        run: echo ${{steps.set-output.outputs.age }}
         
