name: Step Output

on:
 push:
   branches: [main]

jobs:
 job1:
  runs-on: ubuntu-latest

  steps:
    - name: set output
      id: set-output
      shell: bash
      run: |
        echo "name=InterviewPro" >> $GITHUB_OUTPUT
        echo "age=23" >> $GITHUB_OUTPUT

    - name: access output
      run: |
        echo "The value of output name is ${{ steps.set-output.outputs.name }}"
        echo "The value of output age is ${{ steps.set-output.outputs.age }}"
