name: TEST

on:
  push: 
    branches: main

  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          echo ${{ env.GITHUB_REF }}
          echo ${{ github.ref }}

          echo "GITHUB_WORKFLOW - ${{ env.GITHUB_WORKFLOW }}"
          echo "GITHUB_WORKFLOW - ${{ github.workflow }}"
