name: Build Angular App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-angular:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4

      - name: Download artifact of another workflow
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build-angular.yml
          workflow_conclusion: success
          branch: master
          run_number: 12
          name: build-artifact
          if_no_artifact_found: fail
  
